/** Main Moroccan cities (Casablanca first: it has its own delivery fee). Arabic names shown in the AR UI. */
export const CITIES = [
  ['Casablanca', 'الدار البيضاء'],
  ['Rabat', 'الرباط'],
  ['Marrakech', 'مراكش'],
  ['Tanger', 'طنجة'],
  ['Fès', 'فاس'],
  ['Agadir', 'أكادير'],
  ['Meknès', 'مكناس'],
  ['Oujda', 'وجدة'],
  ['Kénitra', 'القنيطرة'],
  ['Tétouan', 'تطوان'],
  ['Salé', 'سلا'],
  ['Témara', 'تمارة'],
  ['Mohammedia', 'المحمدية'],
  ['El Jadida', 'الجديدة'],
  ['Settat', 'سطات'],
  ['Berrechid', 'برشيد'],
  ['Bouskoura', 'بوسكورة'],
  ['Dar Bouazza', 'دار بوعزة'],
  ['Béni Mellal', 'بني ملال'],
  ['Khouribga', 'خريبكة'],
  ['Safi', 'آسفي'],
  ['Essaouira', 'الصويرة'],
  ['Nador', 'الناظور'],
  ['Al Hoceïma', 'الحسيمة'],
  ['Larache', 'العرائش'],
  ['Khémisset', 'الخميسات'],
  ['Taza', 'تازة'],
  ['Errachidia', 'الرشيدية'],
  ['Ouarzazate', 'ورزازات'],
  ['Laâyoune', 'العيون'],
  ['Dakhla', 'الداخلة'],
  ['Guelmim', 'كلميم'],
  ['Tiznit', 'تيزنيت'],
  ['Taroudant', 'تارودانت'],
  ['Ifrane', 'إفران'],
  ['Chefchaouen', 'شفشاون'],
];
